### ISSUE TITLE
WARN: failed to read key file: C:\Users\root\.mmx\wallet.dat

### ISSUE THREAD

**Issue by Drhicom** [madMAx43v3r/mmx-node#89] opened 2022-07-17 03:10 UTC
On a windows 10 machine, making sure the latest Microsoft Visual C++  2015-2022 (both x64 and x86). Installing MMX Node-0.6.25-win64.exe launching the app creating a wallet, looking in the .mmx folder and seeing a wallet_(numbers).dat and rebooting the app

The log lists the following
2022-07-16 22:44:49 [Node] INFO: Starting sync at height 85737
2022-07-16 22:44:49 [Wallet] WARN: failed to read key file: C:\Users\root\ .mmx\wallet.dat    had to put a space in front of the . 
because it took out the \ slash
2022-07-16 22:44:49 [Router] INFO: Connected to peer 23.88.74.202

What file is pointing to the wallet.dat file? When the wallet.json is viewed the correct information "key_file": names the correct in the .mmx directory.

**Comment by madMAx43v3r** [comment] 2022-07-18 01:26
`wallet.dat` is read by default, you have to remove it from the config if you don't want it. it's no big issue though, just a warning.

**Comment by Drhicom** [comment] 2022-07-18 01:49
Which config file points to wallet.dat so I can remove it.

**Comment by madMAx43v3r** [comment] 2022-07-18 12:55
`config/local/Wallet.dat`

**Comment by Jacek-ghub** [comment] 2022-07-19 01:14
I think that some code changes happened around Win v20, and wallet.json is not updated properly with the new code.  I have not seen this error on my box, as I was just upgrading from Win ~v0.6.14.  Although, I worked with @Drhicom to try to nail it down.  (I don't think that the issue is Win specific.)  Here is what we found.

When you do a clean install, the new wallet.json looks like this:
```
{
  "accounts+": [{
      "__type": "mmx.account_t",
      "index": 0,
      "key_file": "wallet_3817250008.dat",
      "name": "jacek-test",
      "num_addresses": 100
    }]
}
```

However, the old (going through upgrades) looks like this:
```
{
  "accounts+": [{
      "__type": "mmx.account_t",
      "index": 0,
      "key_file": "wallet_3817250008.dat",
      "name": "jacek-test",
      "num_addresses": 100
    }],
  "key_files": []
}
```

When a clean install with the latest version is done, that **"key_files": []** entry is never created.  We tried to delete wallet.json, create a new wallet, ...  Nothing worked.  However, the minute that entry is manually added, the warning message goes away.

Hope that helps.

**Comment by Drhicom** [comment] 2022-07-19 13:55
Do you have any record on which version that check was removed?

**Comment by madMAx43v3r** [comment] 2022-07-19 16:27
I think @stotiks had something in place to add `"key_files": []` to the default config on windows, which might not work anymore.

**Comment by Drhicom** [comment] 2022-07-19 21:01
Hello, back from driving around town taking care of things, that's good to hear I hope stotiks can spend some short time to check into this, gladly buy him some beers, we all would like what's best for the project, an error free product will make it more robust. It would be good to have more somewhat testers reporting back on issues that are found out on both sides (windows/linux).

**Comment by stotiks** [comment] 2022-10-10 17:24
Should be fixed

**Comment by Drhicom** [comment] 2022-10-10 19:39
I installed mmx version v0.7.9 fresh on a node. I created a wallet from the seed names and pasted in the farmer reward address and rebooted the mmx app. Log file looks good. When creating the wallet from seed it created a different wallet number. Is that normal?

**Closed** 2022-10-10 22:14 UTC
